<a href="https://colab.research.google.com/github/donicas/ftiproj/blob/main/FTIproj.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [ ]:
# Importance of data, "why should people care?"
# peep geographical patterns that may exist/ per state or region bleh
# context of the areas themselves
# current EPA funding? that could impact area codes
# rural/suberban
# low/high income areas
# map variables

In [2]:
url = 'https://raw.githubusercontent.com/donicas/ftiproj/refs/heads/main/ZipWaterQuality.csv'
df = pd.read_csv(url)
df.head()

,zip,city,state,system_name,pwsid,population,water_source,total_violations,health_violations,unresolved_violations,contaminant_count,health_contaminant_names,latitude,longitude,has_active_issues
0,1001,Agawam,MA,Agawam Water Department,MA1005000,28692.0,SW,1.0,0.0,1.0,0,NaN,42.0702,-72.6227,True
1,1002,Amherst,MA,Amherst Dpw Water Division,MA1008000,39263.0,SW,1.0,1.0,0.0,1,E. coli,42.3671,-72.4646,True
2,1003,Amherst,MA,Amherst Dpw Water Division,MA1008000,39263.0,SW,1.0,1.0,0.0,1,E. coli,42.3919,-72.5248,True
3,1004,Amherst,MA,Amherst Dpw Water Division,MA1008000,39263.0,SW,1.0,1.0,0.0,1,E. coli,42.3845,-72.5132,True
4,1005,Barre,MA,Barre Water Department,MA2021000,4098.0,GW,18.0,0.0,10.0,0,NaN,42.4097,-72.1084,True

In [5]:
df.info()
# water source
#health contaminant names
#has active issues

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41344 entries, 0 to 41343
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   zip                       41344 non-null  int64
 1   city                      41344 non-null  object
 2   state                     41344 non-null  object
 3   system_name               41344 non-null  object
 4   pwsid                     41344 non-null  object
 5   population                41344 non-null  float64
 6   water_source              41343 non-null  object
 7   total_violations          41344 non-null  float64
 8   health_violations         41344 non-null  float64
 9   unresolved_violations     41344 non-null  float64
 10  contaminant_count         41344 non-null  int64
 11  health_contaminant_names  11072 non-null  object
 12  latitude                  41344 non-null  float64
 13  longitude                 41344 non-null  float64
 14  has_active_issues         35100 non-null  object
dtypes: float64(6), int64(2), object(7)
memory usage: 4.7+ MB

In [6]:
df.describe()

,zip,population,total_violations,health_violations,unresolved_violations,contaminant_count,latitude,longitude
count,41344.000000,4.134400e+04,41344.000000,41344.000000,41344.000000,41344.000000,41344.000000,41344.000000
mean,49849.686847,2.301964e+05,6.662539,1.075126,2.474023,0.427099,38.592323,-91.154586
std,27818.005406,8.235376e+05,18.668761,3.556683,9.080675,0.896748,5.236934,15.345359
min,1001.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,19.066800,-176.634000
25%,26447.750000,1.332000e+03,0.000000,0.000000,0.000000,0.000000,35.044300,-97.327700
50%,49049.000000,7.809500e+03,1.000000,0.000000,0.000000,0.000000,39.144250,-87.991750
75%,73103.250000,9.534500e+04,6.000000,1.000000,2.000000,1.000000,41.888200,-80.143400
max,99950.000000,8.271000e+06,292.000000,97.000000,189.000000,8.000000,71.234600,166.641900

In [6]:
df[df.duplicated()]
#no duplicated rows

Empty DataFrame
Columns: [zip, city, state, system_name, pwsid, population, water_source, total_violations, health_violations, unresolved_violations, contaminant_count, health_contaminant_names, latitude, longitude, has_active_issues]
Index: []

In [11]:
df.isna()
# only column here with null (the "true") is health contaminant names, which I feel makes sense but might not
# if null and no contaminations that "makes sense"
# if null and contaminated uh thats weird guys!

,zip,city,state,system_name,pwsid,population,water_source,total_violations,health_violations,unresolved_violations,contaminant_count,health_contaminant_names,latitude,longitude,has_active_issues
0,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41339,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
41340,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
41341,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
41342,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
41343,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [4]:
df_copy = df.copy()

# Health Contaminant focus

In [8]:
df["health_contaminant_names"].describe()

count                11072
unique                 651
top       Stage 2 DBP Rule
freq                  2669
Name: health_contaminant_names, dtype: object

In [10]:
df["health_contaminant_names"].unique()

array([nan, 'E. coli', 'Contaminant 0800',
       'Consumer Confidence Report Rule', 'Total Trihalomethanes (TTHM)',
       'Chlorine residual;Haloacetic Acids (HAA5)',
       'Haloacetic Acids (HAA5)', 'Barium',
       'Consumer Confidence Report Rule;Contaminant 0700', 'HAA6Br',
       'Stage 1 DBP Rule', 'Contaminant 1011',
       'Consumer Confidence Report Rule;Stage 2 DBP Rule;Chlorine residual',
       'Gross Beta;Consumer Confidence Report Rule',
       'Stage 1 DBP Rule;Lead',
       'Stage 2 DBP Rule;Consumer Confidence Report Rule',
       'Lead;Stage 1 DBP Rule',
       'Stage 1 DBP Rule;Consumer Confidence Report Rule;Gross Alpha',
       'Stage 1 DBP Rule;Consumer Confidence Report Rule;Contaminant 0700',
       'Chlorine residual', 'Gross Alpha',
       'Total Trihalomethanes (TTHM);Haloacetic Acids (HAA5);Contaminant 0700;Barium',
       'Combined Radium', 'Gross Beta;Contaminant 0700',
       'Consumer Confidence Report Rule;Barium;Contaminant 0700',
       'Haloacetic Acids (HAA5);E. coli;Contaminant 0700;Gross Beta',
       'Contaminant 0700',
       'Consumer Confidence Report Rule;Combined Radium', 'Nickel',
       'Chlorite',
       'Total Trihalomethanes (TTHM);Stage 1 DBP Rule;Haloacetic Acids (HAA5);Consumer Confidence Report Rule;E. coli',
       'Barium;Consumer Confidence Report Rule',
       'Total Trihalomethanes (TTHM);Consumer Confidence Report Rule;E. coli',
       'Consumer Confidence Report Rule;Barium',
       'Barium;Contaminant 0700', 'Fecal Coliform',
       'Barium;Stage 1 DBP Rule', 'Total Trihalomethanes (TTHM);Barium',
       'Total Trihalomethanes (TTHM);Contaminant 0700',
       'Consumer Confidence Report Rule;Nickel',
       'Total Trihalomethanes (TTHM);Stage 1 DBP Rule;Haloacetic Acids (HAA5);E. coli',
       'Consumer Confidence Report Rule;Stage 1 DBP Rule', 'Bromate',
       'Lead', 'Gross Alpha;Gross Beta', 'Stage 1 DBP Rule;Barium',
       'Haloacetic Acids (HAA5);Total Trihalomethanes (TTHM)',
       'Haloacetic Acids (HAA5);Gross Alpha;Fecal Coliform',
       'Consumer Confidence Report Rule;Fecal Coliform',
       'Stage 1 DBP Rule;Consumer Confidence Report Rule',
       'Haloacetic Acids (HAA5);Gross Alpha',
       'Barium;Fecal Coliform;Haloacetic Acids (HAA5)',
       'Consumer Confidence Report Rule;Haloacetic Acids (HAA5)',
       'Haloacetic Acids (HAA5);Stage 1 DBP Rule;Total Trihalomethanes (TTHM);E. coli',
       'Stage 1 DBP Rule;Haloacetic Acids (HAA5);Gross Alpha',
       'Fecal Coliform;Haloacetic Acids (HAA5)',
       'Total Trihalomethanes (TTHM);Haloacetic Acids (HAA5)', 'Selenium',
       'Haloacetic Acids (HAA5);Consumer Confidence Report Rule;Total Trihalomethanes (TTHM);E. coli',
       'Stage 2 DBP Rule',
       'Consumer Confidence Report Rule;Stage 2 DBP Rule',
       'Consumer Confidence Report Rule;Stage 2 DBP Rule;Contaminant 0700',
       'Stage 2 DBP Rule;Consumer Confidence Report Rule;Barium',
       'Consumer Confidence Report Rule;Stage 2 DBP Rule;Stage 1 DBP Rule',
       'Stage 2 DBP Rule;Haloacetic Acids (HAA5)',
       'Stage 2 DBP Rule;Barium', 'Stage 1 DBP Rule;Stage 2 DBP Rule',
       'Haloacetic Acids (HAA5);Stage 1 DBP Rule',
       'Stage 2 DBP Rule;Contaminant 0700',
       'Stage 1 DBP Rule;Consumer Confidence Report Rule;Stage 2 DBP Rule',
       'Stage 2 DBP Rule;Consumer Confidence Report Rule;Contaminant 0700',
       'Stage 2 DBP Rule;Combined Radium;Consumer Confidence Report Rule',
       'Consumer Confidence Report Rule;Contaminant 0700;Stage 2 DBP Rule',
       'Haloacetic Acids (HAA5);E. coli',
       'Stage 1 DBP Rule;Lead;Fecal Coliform', 'Stage 1 DBP Rule;E. coli',
       'Stage 1 DBP Rule;Contaminant 1009',
       'Stage 1 DBP Rule;Gross Alpha',
       'Stage 1 DBP Rule;Gross Beta;Gross Alpha',
       'Stage 1 DBP Rule;Fecal Coliform;Haloacetic Acids (HAA5)',
       'Stage 1 DBP Rule;E. coli;Haloacetic Acids (HAA5)',
       'Contaminant 2806', 'Contaminant 2806;Chloroform;Contaminant 1017',
       'Chloroform;Contaminant 2806;Contaminant 1017', 'Contaminant 1017',
       'Contaminant 1017;Contaminant 1095',
       'Contaminant 1028;Contaminant 1032', 'Chloroform;Contaminant 1017',
       'Contaminant 2806;Contaminant 0700', 'Chloroform',
       'Contaminant 1028;Contaminant 2806;Contaminant 1032',
       'Stage 2 DBP Rule;Total Trihalomethanes (TTHM)',
       'Total Trihalomethanes (TTHM);Consumer Confidence Report Rule',
       'Contaminant 1017;Contaminant 1032;Contaminant 1028',
       'Total Trihalomethanes (TTHM);Haloacetic Acids (HAA5);Stage 2 DBP Rule',
       'Total Trihalomethanes (TTHM);Haloacetic Acids (HAA5);Fecal Coliform;Contaminant 2650',
       'Haloacetic Acids (HAA5);Contaminant 2806',
       'Contaminant 1032;Chloroform', 'Chlorite;Haloacetic Acids (HAA5)',
       'Stage 2 DBP Rule;Contaminant 2806', 'Barium;Stage 2 DBP Rule',
       'Contaminant 1028', 'Stage 2 DBP Rule;Contaminant 1028;E. coli',
       'Chloroform;Contaminant 2806',
       'Contaminant 2806;Contaminant 1028;Chloroform',
       'Contaminant 2806;Consumer Confidence Report Rule;Chloroform',
       'Copper;Chloroform', 'Contaminant 1032',
       'Haloacetic Acids (HAA5);Consumer Confidence Report Rule;Stage 2 DBP Rule;Stage 1 DBP Rule;Contaminant 1920',
       'E. coli;Fecal Coliform;Haloacetic Acids (HAA5)',
       'Chlorine residual;Fecal Coliform',
       'Haloacetic Acids (HAA5);Total Trihalomethanes (TTHM);Stage 2 DBP Rule',
       'Contaminant 1028;Stage 2 DBP Rule',
       'Haloacetic Acids (HAA5);Fecal Coliform;Contaminant 1920',
       'Contaminant 1920;Stage 2 DBP Rule',
       'Contaminant 1920;Contaminant 1028',
       'Total Trihalomethanes (TTHM);Fecal Coliform;Haloacetic Acids (HAA5)',
       'Haloacetic Acids (HAA5);Consumer Confidence Report Rule',
       'Chlorate', 'Consumer Confidence Report Rule;Contaminant 2806',
       'Stage 1 DBP Rule;Haloacetic Acids (HAA5)',
       'Haloacetic Acids (HAA5);Chlorine residual',
       'Barium;Stage 1 DBP Rule;Stage 2 DBP Rule;E. coli;HAA6Br',
       'Contaminant 2214', 'Stage 2 DBP Rule;Chloroform',
       'Chloroform;Contaminant 2806;Stage 1 DBP Rule',
       'Contaminant 2806;Stage 2 DBP Rule',
       'Fecal Coliform;Contaminant 1028', 'Gross Beta',
       'Contaminant 1032;Stage 2 DBP Rule;Contaminant 1028',
       'Haloacetic Acids (HAA5);Contaminant 2806;Chloroform',
       'Chloroform;Contaminant 1017;Contaminant 2806;Barium',
       'Stage 2 DBP Rule;Contaminant 1905', 'Contaminant 1905',
       'Stage 1 DBP Rule;Stage 2 DBP Rule;Haloacetic Acids (HAA5)',
       'Haloacetic Acids (HAA5);Total Trihalomethanes (TTHM);Contaminant 1022',
       'Fecal Coliform;Contaminant 1028;Contaminant 1032',
       'Contaminant 1022',
       'Total Trihalomethanes (TTHM);Haloacetic Acids (HAA5);Contaminant 1028',
       'E. coli;Chloroform;Contaminant 2806',
       'Total Trihalomethanes (TTHM);Stage 2 DBP Rule',
       'Barium;E. coli;Contaminant 0800', 'E. coli;Stage 1 DBP Rule',
       'Total Trihalomethanes (TTHM);Chlorine residual',
       'Lead;Contaminant 0700', 'Stage 2 DBP Rule;Chlorine residual',
       'Lead;Stage 2 DBP Rule', 'Stage 2 DBP Rule;Contaminant 2049',
       'Contaminant 2216;Contaminant 2210',
       'Haloacetic Acids (HAA5);Stage 2 DBP Rule',
       'Contaminant 1028;Contaminant 1032;Contaminant 1095;Contaminant 1017',
       'Haloacetic Acids (HAA5);Contaminant 2214',
       'Contaminant 1032;Contaminant 1028',
       'Fecal Coliform;Contaminant 0700',
       'Consumer Confidence Report Rule;Contaminant 0700;Chlorite',
       'Contaminant 0700;Haloacetic Acids (HAA5);Chlorite',
       'Contaminant 0700;Consumer Confidence Report Rule',
       'Fecal Coliform;Chlorite;Contaminant 0700',
       'Haloacetic Acids (HAA5);Consumer Confidence Report Rule;Contaminant 0700',
       'Contaminant 0700;Fecal Coliform;E. coli;Consumer Confidence Report Rule',
       'E. coli;Total Trihalomethanes (TTHM)',
       'Consumer Confidence Report Rule;Atrazine',
       'Total Trihalomethanes (TTHM);Contaminant 0800',
       'E. coli;Contaminant 0700;Stage 1 DBP Rule',
       'Contaminant 0700;Haloacetic Acids (HAA5);Stage 1 DBP Rule',
       'Chlorite;E. coli',
       'Chlorite;Haloacetic Acids (HAA5);Consumer Confidence Report Rule',
       'Consumer Confidence Report Rule;Contaminant 1085',
       'E. coli;Contaminant 0700', 'Contaminant 0700;Stage 1 DBP Rule',
       'Contaminant 0700;Consumer Confidence Report Rule;Stage 1 DBP Rule',
       'Fecal Coliform;Chlorite', 'Chlorite;Total Trihalomethanes (TTHM)',
       'Contaminant 0700;Barium',
       'Contaminant 0700;Consumer Confidence Report Rule;Lead',
       'Consumer Confidence Report Rule;E. coli',
       'Contaminant 0700;Total Trihalomethanes (TTHM)',
       'Chlorodibromoacetic Acid', 'Gross Beta;Lead',
       'Fecal Coliform;Consumer Confidence Report Rule',
       'Stage 1 DBP Rule;Contaminant 0700',
       'Haloacetic Acids (HAA5);Contaminant 0700',
       'Contaminant 0700;Barium;HAA6Br',
       'Consumer Confidence Report Rule;Total Trihalomethanes (TTHM)',
       'Fecal Coliform;Contaminant 0700;Consumer Confidence Report Rule;E. coli',
       'Contaminant 0800;E. coli',
       'Consumer Confidence Report Rule;Contaminant 1032',
       'Consumer Confidence Report Rule;E. coli;Haloacetic Acids (HAA5)',
       'Contaminant 0700;Stage 2 DBP Rule', 'Chromium',
       'Stage 2 DBP Rule;Fecal Coliform;Total Trihalomethanes (TTHM)',
       'Stage 2 DBP Rule;Total Trihalomethanes (TTHM);Haloacetic Acids (HAA5)',
       'Total Trihalomethanes (TTHM);Stage 2 DBP Rule;Chlorite;Haloacetic Acids (HAA5)',
       'Stage 2 DBP Rule;Haloacetic Acids (HAA5);Contaminant 0800',
       'Total Trihalomethanes (TTHM);Consumer Confidence Report Rule;Chlorine residual',
       'Contaminant 0700;Haloacetic Acids (HAA5)',
       'Combined Radium;Gross Alpha',
       'Haloacetic Acids (HAA5);Contaminant 0700;Total Trihalomethanes (TTHM);Contaminant 0800',
       'Total Trihalomethanes (TTHM);Contaminant 0700;Consumer Confidence Report Rule',
       'Total Trihalomethanes (TTHM);Contaminant 0800;Fecal Coliform',
       'Fecal Coliform;Contaminant 0800', 'Stage 1 DBP Rule;Chlorite',
       'Haloacetic Acids (HAA5);Fecal Coliform;Contaminant 0800',
       'Contaminant 0800;Fecal Coliform',
       'Consumer Confidence Report Rule;Contaminant 0800',
       'Fecal Coliform;Chlorite;Chlorine residual;Contaminant 0800',
       'Lead;Contaminant 0700;Chlorine residual',
       'Lead;Contaminant 0700;Chlorite;Chlorine residual',
       'Contaminant 0700;E. coli',
       'Total Trihalomethanes (TTHM);Fecal Coliform;Contaminant 0800',
       'Stage 1 DBP Rule;Contaminant 0800',
       'Haloacetic Acids (HAA5);Contaminant 0800',
       'Fecal Coliform;Consumer Confidence Report Rule;Contaminant 0800;Total Trihalomethanes (TTHM)',
       'Total Trihalomethanes (TTHM);Stage 1 DBP Rule;Contaminant 0700;Consumer Confidence Report Rule',
       'Contaminant 0700;Contaminant 0800',
       'Haloacetic Acids (HAA5);Contaminant 0800;Total Trihalomethanes (TTHM)',
       'Haloacetic Acids (HAA5);Chlorine residual;Contaminant 0800',
       'Consumer Confidence Report Rule;Haloacetic Acids (HAA5);Fecal Coliform;Contaminant 0800',
       'Chlorite;Contaminant 0700;Contaminant 0800',
       'Contaminant 0700;HAA6Br;Consumer Confidence Report Rule',
       'Chlorite;Contaminant 0800;Contaminant 0700',
       'Consumer Confidence Report Rule;Total Trihalomethanes (TTHM);Chlorine residual;Contaminant 0800',
       'E. coli;Fecal Coliform',
       'Total Trihalomethanes (TTHM);Haloacetic Acids (HAA5);Contaminant 0800',
       'Chlorite;Consumer Confidence Report Rule;Fecal Coliform;Contaminant 0800;Chlorine residual',
       'Fecal Coliform;Total Trihalomethanes (TTHM)',
       'Haloacetic Acids (HAA5);Chlorite;Contaminant 0800',
       'Fecal Coliform;Contaminant 0800;Chlorite',
       'Chlorite;Fecal Coliform', 'Chlorite;Contaminant 0800',
       'Chlorite;Chlorine residual',
       'Haloacetic Acids (HAA5);Total Trihalomethanes (TTHM);Contaminant 0800',
       'Contaminant 0700;Chlorite;Chlorine residual',
       'Chlorine residual;Contaminant 0800',
       'Contaminant 0800;Consumer Confidence Report Rule',
       'Fecal Coliform;Stage 1 DBP Rule;Chlorite;Consumer Confidence Report Rule;Total Trihalomethanes (TTHM);Chlorine residual',
       'Fecal Coliform;E. coli',
       'Fecal Coliform;Contaminant 0800;E. coli',
       'Haloacetic Acids (HAA5);Stage 2 DBP Rule;Total Trihalomethanes (TTHM)',
       'Chlorite;Stage 2 DBP Rule',
       'Total Trihalomethanes (TTHM);Haloacetic Acids (HAA5);Consumer Confidence Report Rule',
       'Haloacetic Acids (HAA5);Chlorite',
       'Consumer Confidence Report Rule;Gross Alpha',
       'Stage 2 DBP Rule;Gross Alpha', 'Combined Radium;Stage 2 DBP Rule',
       'Contaminant 2946;Stage 2 DBP Rule',
       'Stage 2 DBP Rule;Haloacetic Acids (HAA5);Stage 1 DBP Rule',
       'Total Trihalomethanes (TTHM);Stage 2 DBP Rule;Haloacetic Acids (HAA5)',
       'Haloacetic Acids (HAA5);Stage 2 DBP Rule;Contaminant 2946',
       'Stage 2 DBP Rule;Lead', 'Total Trihalomethanes (TTHM);Lead',
       'Total Trihalomethanes (TTHM);Haloacetic Acids (HAA5);Combined Radium;Stage 2 DBP Rule',
       'Haloacetic Acids (HAA5);Stage 2 DBP Rule;Fecal Coliform',
       'Stage 2 DBP Rule;E. coli', 'Stage 2 DBP Rule;Fecal Coliform',
       'Stage 2 DBP Rule;E. coli;Fecal Coliform',
       'Stage 2 DBP Rule;Stage 1 DBP Rule',
       'Stage 1 DBP Rule;Total Trihalomethanes (TTHM);Stage 2 DBP Rule',
       'Stage 1 DBP Rule;Stage 2 DBP Rule;Total Trihalomethanes (TTHM);Coliform (TCR);Contaminant 0800',
       'Consumer Confidence Report Rule;Contaminant 1009',
       'Chlorine residual;Stage 2 DBP Rule',
       'Consumer Confidence Report Rule;Gross Beta',
       'Total Trihalomethanes (TTHM);Gross Beta',
       'Gross Beta;Gross Alpha', 'Uranium',
       'Contaminant 1009;Consumer Confidence Report Rule',
       'Total Trihalomethanes (TTHM);Haloacetic Acids (HAA5);Lead',
       'Contaminant 1085;Stage 2 DBP Rule', 'Stage 2 DBP Rule;Nitrate',
       'Nitrate',
       'Consumer Confidence Report Rule;Total Trihalomethanes (TTHM);Stage 2 DBP Rule',
       'Consumer Confidence Report Rule;Haloacetic Acids (HAA5);Fecal Coliform',
       'Contaminant 2946', 'Stage 2 DBP Rule;Cadmium',
       'Gross Alpha;Combined Radium',
       'Total Trihalomethanes (TTHM);Fecal Coliform',
       'Consumer Confidence Report Rule;Stage 2 DBP Rule;Total Coliform',
       'Bromochloroacetic Acid', 'Contaminant 0800;Contaminant 1008',
       'Haloacetic Acids (HAA5);Fecal Coliform',
       'Haloacetic Acids (HAA5);Stage 2 DBP Rule;Contaminant 0700',
       'Total Trihalomethanes (TTHM);Stage 2 DBP Rule;Contaminant 0700;Consumer Confidence Report Rule',
       'Total Trihalomethanes (TTHM);Stage 2 DBP Rule;Contaminant 0700',
       'Stage 1 DBP Rule;Fecal Coliform;Haloacetic Acids (HAA5);Total Trihalomethanes (TTHM);Contaminant 0700;Contaminant 0800',
       'Total Trihalomethanes (TTHM);Chlorite',
       'Haloacetic Acids (HAA5);Total Trihalomethanes (TTHM);Consumer Confidence Report Rule',
       'Stage 2 DBP Rule;Contaminant 0800;Contaminant 0700',
       'Chlorite;Haloacetic Acids (HAA5);Stage 2 DBP Rule',
       'Fecal Coliform;Chlorine residual;Stage 2 DBP Rule',
       'Stage 2 DBP Rule;Contaminant 0800',
       'Fecal Coliform;Chlorine residual',
       'Stage 2 DBP Rule;Stage 1 DBP Rule;Fecal Coliform;Contaminant 0800',
       'Contaminant 0700;Stage 2 DBP Rule;Consumer Confidence Report Rule',
       'Chlorine residual;Contaminant 0700',
       'Consumer Confidence Report Rule;Stage 2 DBP Rule;Haloacetic Acids (HAA5)',
       'Stage 2 DBP Rule;Contaminant 0700;Consumer Confidence Report Rule',
       'Contaminant 0700;Haloacetic Acids (HAA5);Stage 2 DBP Rule',
       'Stage 1 DBP Rule;Contaminant 0700;Stage 2 DBP Rule',
       'Contaminant 0700;Chlorine residual',
       'Consumer Confidence Report Rule;Stage 1 DBP Rule;Stage 2 DBP Rule;Contaminant 0700',
       'Haloacetic Acids (HAA5);Consumer Confidence Report Rule;Total Trihalomethanes (TTHM);Fecal Coliform',
       'Total Trihalomethanes (TTHM);Stage 1 DBP Rule',
       'Stage 2 DBP Rule;Chlorine residual;Contaminant 0700',
       'Stage 1 DBP Rule;Stage 2 DBP Rule;Contaminant 0700',
       'Gross Beta;Stage 2 DBP Rule',
       'Stage 1 DBP Rule;E. coli;Contaminant 0800;Fecal Coliform',
       'Lead;Chlorine residual', 'Copper',
       'E. coli;Total Trihalomethanes (TTHM);Haloacetic Acids (HAA5)',
       'Contaminant 2257', 'Contaminant 0800;Contaminant 2257',
       'Barium;Copper;Gross Beta', 'Contaminant 0700;Copper',
       'Consumer Confidence Report Rule;Chlorine residual',
       'Copper;Chlorine residual',
       'Stage 2 DBP Rule;Chlorine residual;Atrazine',
       'Stage 1 DBP Rule;Gross Beta',
       'Gross Alpha;Gross Beta;Stage 2 DBP Rule',
       'Stage 2 DBP Rule;Barium;Chlorine residual', 'Radium-226;Barium',
       'Cadmium;Gross Beta', 'Stage 2 DBP Rule;Gross Beta',
       'Barium;Stage 1 DBP Rule;Stage 2 DBP Rule',
       'Stage 2 DBP Rule;Atrazine', 'Stage 1 DBP Rule;Chlorine residual',
       'Stage 2 DBP Rule;Consumer Confidence Report Rule;Stage 1 DBP Rule',
       'Consumer Confidence Report Rule;Stage 1 DBP Rule;Stage 2 DBP Rule',
       'Stage 2 DBP Rule;Bromate',
       'Atrazine;Stage 2 DBP Rule;Contaminant 0700',
       'Gross Beta;Chlorine residual', 'Arsenic',
       'Lead;Stage 2 DBP Rule;Chlorine residual',
       'Stage 2 DBP Rule;Barium;Contaminant 0700;Chlorine residual',
       'Stage 1 DBP Rule;Stage 2 DBP Rule;Chlorine residual',
       'Stage 1 DBP Rule;Chlorine residual;Stage 2 DBP Rule',
       'Consumer Confidence Report Rule;Chlorine residual;Contaminant 0700',
       'Stage 1 DBP Rule;Consumer Confidence Report Rule;Stage 2 DBP Rule;Chlorine residual;Contaminant 0700',
       'Consumer Confidence Report Rule;Contaminant 0700;Gross Alpha',
       'Contaminant 0700;Stage 1 DBP Rule;Arsenic;E. coli',
       'Contaminant 0700;Stage 1 DBP Rule;Arsenic',
       'E. coli;Haloacetic Acids (HAA5)',
       'Haloacetic Acids (HAA5);Consumer Confidence Report Rule;Total Trihalomethanes (TTHM);Contaminant 0800',
       'Arsenic;Consumer Confidence Report Rule',
       'Haloacetic Acids (HAA5);Atrazine', 'Contaminant 4109',
       'Stage 2 DBP Rule;Contaminant 4109;Gross Beta',
       'Stage 2 DBP Rule;Contaminant 1028;Stage 1 DBP Rule',
       'Stage 1 DBP Rule;Nickel',
       'Gross Beta;Stage 2 DBP Rule;Stage 1 DBP Rule', 'Mercury',
       'Haloacetic Acids (HAA5);Stage 1 DBP Rule;Total Trihalomethanes (TTHM)',
       'Barium;Stage 2 DBP Rule;Stage 1 DBP Rule',
       'Stage 1 DBP Rule;Haloacetic Acids (HAA5);Barium',
       'Fecal Coliform;Stage 2 DBP Rule;Chlorite;Haloacetic Acids (HAA5)',
       'Haloacetic Acids (HAA5);Barium',
       'Haloacetic Acids (HAA5);Chlorine residual;Total Trihalomethanes (TTHM)',
       'Gross Beta;Consumer Confidence Report Rule;Contaminant 0700',
       'Gross Beta;Contaminant 0700;Chlorine residual',
       'Gross Beta;Haloacetic Acids (HAA5)',
       'Haloacetic Acids (HAA5);Total Trihalomethanes (TTHM);Chlorine residual',
       'Total Trihalomethanes (TTHM);Haloacetic Acids (HAA5);Chlorine residual',
       'Contaminant 0700;Consumer Confidence Report Rule;Chlorine residual',
       'Contaminant 1009;Contaminant 0800',
       'Fecal Coliform;E. coli;Contaminant 1009;Haloacetic Acids (HAA5)',
       'Contaminant 1009', 'Contaminant 1008',
       'Fecal Coliform;Total Trihalomethanes (TTHM);Chlorite;Haloacetic Acids (HAA5)',
       'Total Trihalomethanes (TTHM);Chlorite;Contaminant 1009',
       'Haloacetic Acids (HAA5);Revised Total Coliform Rule;Contaminant 1006',
       'Consumer Confidence Report Rule;Total Trihalomethanes (TTHM);Fecal Coliform',
       'Gross Beta;Bromochloroacetic Acid', 'Contaminant 1045',
       'Lead;Contaminant 0700;Consumer Confidence Report Rule',
       'Lead;Consumer Confidence Report Rule',

In [11]:
df[['population', 'unresolved_violations', 'health_contaminant_names']]
# population correlate with unresolved issues/contaniment type(s)?

,population,unresolved_violations,health_contaminant_names
0,28692.0,1.0,NaN
1,39263.0,0.0,E. coli
2,39263.0,0.0,E. coli
3,39263.0,0.0,E. coli
4,4098.0,10.0,NaN
...,...,...,...
41339,8937.0,0.0,NaN
41340,3218.0,0.0,NaN
41341,100.0,7.0,NaN
41342,2300.0,0.0,Total Trihalomethanes (TTHM);Stage 2 DBP Rule
41343,8937.0,12.0,E. coli;Total Trihalomethanes (TTHM)

# Duplicate dropping nulls (all of the nan contaminations!!)

In [12]:
df_copy.dropna()
# so i had an idea and thought "in case this dropped something that wasnt the health contaminat names, i will be redoing this operation to check (in another method)"

,zip,city,state,system_name,pwsid,population,water_source,total_violations,health_violations,unresolved_violations,contaminant_count,health_contaminant_names,latitude,longitude,has_active_issues
1,1002,Amherst,MA,Amherst Dpw Water Division,MA1008000,39263.0,SW,1.0,1.0,0.0,1,E. coli,42.3671,-72.4646,True
2,1003,Amherst,MA,Amherst Dpw Water Division,MA1008000,39263.0,SW,1.0,1.0,0.0,1,E. coli,42.3919,-72.5248,True
3,1004,Amherst,MA,Amherst Dpw Water Division,MA1008000,39263.0,SW,1.0,1.0,0.0,1,E. coli,42.3845,-72.5132,True
9,1011,Chester,MA,Chester Water Department,MA1059000,750.0,SW,3.0,1.0,2.0,1,Contaminant 0800,42.2794,-72.9888,True
44,1069,Palmer,MA,Palmer Water District No.1,MA1227000,4789.0,SW,2.0,2.0,2.0,1,E. coli,42.1762,-72.3288,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41334,99919,Thorne Bay,AK,"City of Thorne Bay,",AK2120216,470.0,SW,28.0,1.0,4.0,1,Total Trihalomethanes (TTHM),55.6609,-132.5138,False
41336,99922,Hydaburg,AK,Hydaburg,AK2120224,415.0,SW,83.0,6.0,15.0,1,Total Trihalomethanes (TTHM),55.2087,-132.8259,True
41338,99925,Klawock,AK,Klawock,AK2120169,904.0,SW,26.0,19.0,20.0,1,Total Trihalomethanes (TTHM),55.5526,-133.0555,True
41342,99929,Wrangell,AK,Wrangell,AK2120143,2300.0,SW,6.0,3.0,0.0,2,Total Trihalomethanes (TTHM);Stage 2 DBP Rule,56.4335,-132.3529,False
41343,99950,Ketchikan,AK,Ketchikan Public Utilities,AK2120232,8937.0,SW,34.0,4.0,12.0,2,E. coli;Total Trihalomethanes (TTHM),55.3422,-131.6478,True

In [14]:
df_copy_two = df.copy()
df_copy_two.dropna(subset=["health_contaminant_names"])
# now this copy has null values that're coming from somewhere else possibilities=(water source (1)/has active issues(multiple))

,zip,city,state,system_name,pwsid,population,water_source,total_violations,health_violations,unresolved_violations,contaminant_count,health_contaminant_names,latitude,longitude,has_active_issues
1,1002,Amherst,MA,Amherst Dpw Water Division,MA1008000,39263.0,SW,1.0,1.0,0.0,1,E. coli,42.3671,-72.4646,True
2,1003,Amherst,MA,Amherst Dpw Water Division,MA1008000,39263.0,SW,1.0,1.0,0.0,1,E. coli,42.3919,-72.5248,True
3,1004,Amherst,MA,Amherst Dpw Water Division,MA1008000,39263.0,SW,1.0,1.0,0.0,1,E. coli,42.3845,-72.5132,True
9,1011,Chester,MA,Chester Water Department,MA1059000,750.0,SW,3.0,1.0,2.0,1,Contaminant 0800,42.2794,-72.9888,True
44,1069,Palmer,MA,Palmer Water District No.1,MA1227000,4789.0,SW,2.0,2.0,2.0,1,E. coli,42.1762,-72.3288,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41334,99919,Thorne Bay,AK,"City of Thorne Bay,",AK2120216,470.0,SW,28.0,1.0,4.0,1,Total Trihalomethanes (TTHM),55.6609,-132.5138,False
41336,99922,Hydaburg,AK,Hydaburg,AK2120224,415.0,SW,83.0,6.0,15.0,1,Total Trihalomethanes (TTHM),55.2087,-132.8259,True
41338,99925,Klawock,AK,Klawock,AK2120169,904.0,SW,26.0,19.0,20.0,1,Total Trihalomethanes (TTHM),55.5526,-133.0555,True
41342,99929,Wrangell,AK,Wrangell,AK2120143,2300.0,SW,6.0,3.0,0.0,2,Total Trihalomethanes (TTHM);Stage 2 DBP Rule,56.4335,-132.3529,False
41343,99950,Ketchikan,AK,Ketchikan Public Utilities,AK2120232,8937.0,SW,34.0,4.0,12.0,2,E. coli;Total Trihalomethanes (TTHM),55.3422,-131.6478,True